# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/railfence.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.railfence = QtWidgets.QTabWidget(self.centralwidget)
        self.railfence.setGeometry(QtCore.QRect(10, 30, 721, 511))
        self.railfence.setObjectName("railfence")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(60, 70, 51, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(60, 120, 51, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(60, 170, 51, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(270, 30, 111, 31))
        self.label_4.setObjectName("label_4")
        self.txt_plain = QtWidgets.QTextEdit(self.tab)
        self.txt_plain.setGeometry(QtCore.QRect(230, 60, 371, 71))
        self.txt_plain.setObjectName("txt_plain")
        self.txt_key = QtWidgets.QTextEdit(self.tab)
        self.txt_key.setGeometry(QtCore.QRect(230, 150, 371, 41))
        self.txt_key.setObjectName("txt_key")
        self.txt_cipher = QtWidgets.QTextEdit(self.tab)
        self.txt_cipher.setGeometry(QtCore.QRect(230, 210, 371, 61))
        self.txt_cipher.setObjectName("txt_cipher")
        self.btn_encrypt = QtWidgets.QPushButton(self.tab)
        self.btn_encrypt.setGeometry(QtCore.QRect(220, 320, 75, 23))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_decrypt = QtWidgets.QPushButton(self.tab)
        self.btn_decrypt.setGeometry(QtCore.QRect(470, 320, 75, 23))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.railfence.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.railfence.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Plain Text"))
        self.label_2.setText(_translate("MainWindow", "Key"))
        self.label_3.setText(_translate("MainWindow", "Cipher Tẽt"))
        self.label_4.setText(_translate("MainWindow", "railfence"))
        self.btn_encrypt.setText(_translate("MainWindow", "Mã hoá"))
        self.btn_decrypt.setText(_translate("MainWindow", "Giải mã"))
        self.railfence.setTabText(self.railfence.indexOf(self.tab), _translate("MainWindow", "railfence"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
